### ISSUE TITLE
我感觉可以加一栏 比较好的开源库topXXX....

### ISSUE THREAD

**Issue by JustinFincher** [Node-X/trip-to-iOS#1]
比如看这个？
http://github.ibireme.com/github/list/ios/

**Comment by wzhudev** [comment]
我记得那个 repo 里面有个 top100.md，你要不看下？这个可以有。

不过我还处在学 OC 和 Swift 的阶段，决定将后者作为主力语言。

**Comment by JustinFincher** [comment]
@wendzhue OK 我估计还是OC....现在OC我半生不熟 还是先搞OC...
另: http://github.ibireme.com/github/list/ios/ 现已加入 http://startpage.daoapp.io/ 全家桶 (ios栏目下)
关于TopXX的 我会在考完试加上去

**Comment by rhythm1995** [comment]
现在考试真是累的一比，其实我想先写一个自己的博客，然后再把Nodex的主页重写一下，把论坛加成其中一个内容。

**Comment by JustinFincher** [comment]
办公司！诺德克

发自我的 iPhone

**Comment by wzhudev** [comment]
要不叫诺德克斯。

**Comment by oceanjaya** [comment]
我们又不是外资公司 为毛中文直译……

**Comment by JustinFincher** [comment]
因为如果直接翻译为 “节点X” 公司 太奇怪了 没人能知道是什么意思

发自我的 iPhone

**Comment by oceanjaya** [comment]
当然这也不是我的主张… 建议再想个中文名 不是音译也不是直译

**Comment by JustinFincher** [comment]
那样就更奇怪了 中英文没有任何关联

发自我的 iPhone

**Comment by oceanjaya** [comment]
关联性不是重点 甚至不要中文名都行 关键是别把外包公司做成皮包公司

**Comment by oceanjaya** [comment]
还有……  这不适合讨论这个… 其他人手机要响爆了

**Comment by JustinFincher** [comment]
好吧 不过话说回来 我原本就是准备做一个皮包公司 空壳的 毕竟现在我们什么也没有
